### ISSUE TITLE
Cannot click Again

### ISSUE THREAD

**Issue by gsolanki1509** [tonylukasavage/path.animator#10]
I having been using this module throughout my whole project.
If i open the window for first time, its opening perfectly. And i have a requirement that clicking on these sub menus i have to open another window (which i am doing successfully). But suppose i move back to last window and again try to open this menu then am unable to open it.

Can you please tell me, if am doing anything wrong.

Thanks,

**Comment by nicolomonili** [comment]
@gsolanki1509 I think you're wrong the repository.. Maybe this https://github.com/tonylukasavage/pathmenu.js ?
