### ISSUE TITLE
Create a path.animator object from Ti.UI.createButton

### ISSUE THREAD

**Issue by nicolomonili** [tonylukasavage/path.animator#11]
First of all thanks for this module !

Could you add the possibility to create a "path.animator" object from Ti.UI.createButton ? (without add the button to a view) Because now the only way to create a "path.animator" object is to use a view , correct?

Thanks

**Comment by jasonkneen** [comment]
Not sure I understand the issue. What are you trying to achieve?

**Comment by nicolomonili** [comment]
Thanks for the reply , i mean this


    var RotationModule = require('path.animator');

    var btn = RotationModule.createButton({  <--- not only creteView
        width: 20,
        height: 20,
        backgroundImage : ".."
    });

**Comment by jasonkneen** [comment]
Ok - but why? If want a button can't you add that to the animated view?

I'm not understanding why you need a button

**Comment by nicolomonili** [comment]
Of course i can do that in fact (now already do), i asked to be able to add the rotation event directly to the button ... It is a little thing effectively
 ...
